# FIXME - CI currently runs for dev and dsl2 branches, remove the latter before merging to dev
actions_ci: False
files_exist:
  - bin/markdown_to_html.py
files_unchanged:
  - .gitattributes
repository_type: pipeline
