# FIXME - CI currently runs for dev and dsl2 branches, remove the latter before merging to dev
repository_type: pipeline
lint:
  files_unchanged:
    - .gitattributes
  files_exist:
    - bin/markdown_to_html.py
  actions_ci: False
