name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Get Minimum supported Nextflow version
        id: get_version
        run: |
          VERSION=$(grep 'nextflowVersion' nextflow.config | awk -F'= ' '{print $2}' | tr -d '!>=" ')
          echo "::set-output name=version::$VERSION"

  test:
    name: Run ${{ matrix.profile }} pipeline test
    needs: get_version

    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/fetchngs') }}"

    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ needs.get_version.outputs.version }}

    strategy:
      matrix:
        profile: ["docker"]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Use Nextflow version
        run: echo "Using Nextflow version $NXF_VER"

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: ./test-datasets/
          key: methylseq-test-data

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: methylseq
          path: ./test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ./test-datasets/samplesheet/*csv; do
            sed -i 's=https://github.com/nf-core/test-datasets/raw/methylseq/=./test-datasets/=g' $f
            sed -i 's=https://raw.githubusercontent.com/nf-core/test-datasets/methylseq/=./test-datasets/=g' $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Run nf-test
        run: |
          nf-test test \
            --profile=test_ci,test,${{ matrix.profile }} \
            tests/${{ matrix.aligner }}/*.nf.test \
            --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap
