name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test-dev:
    if: github.base_ref == 'dev' || github.event_name == 'push'
    name: Run pipeline with test data on dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER: ["latest-everything"]
        aligner: ["bismark", "bismark_hisat", "bwameth"]
        profile: ["docker"] # TODO , "singularity", "conda"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: ./test-datasets/
          key: methylseq-test-data

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: methylseq
          path: ./test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ./test-datasets/samplesheet/*csv; do
            sed -i 's=https://github.com/nf-core/test-datasets/raw/methylseq/=./test-datasets/=g' $f
            sed -i 's=https://raw.githubusercontent.com/nf-core/test-datasets/methylseq/=./test-datasets/=g' $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: |
          nf-test test tests/pipeline/${{ matrix.aligner }}/ --tap=test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/methylseq/methylseq/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      # Comment on the PR with the test results
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: test.tap

  test-master:
    if: github.base_ref == 'master'
    name: Run pipeline with test data on master
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER: ["22.10.1", "latest-everything"]
        aligner: ["bismark", "bismark_hisat", "bwameth"]
        profile: ["docker"] # TODO , "singularity", "conda"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: ./test-datasets/
          key: methylseq-test-data

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: methylseq
          path: ./test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ./test-datasets/samplesheet/*csv; do
            sed -i 's=https://github.com/nf-core/test-datasets/raw/methylseq/=./test-datasets/=g' $f
            sed -i 's=https://raw.githubusercontent.com/nf-core/test-datasets/methylseq/=./test-datasets/=g' $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/methylseq/methylseq/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      # Comment on the PR with the test results
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: test.tap
